export const COUNTRY_OPTIONS = [
  "Worldwide",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Belarus",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Brazil",
  "Brunei",
  "Cambodia",
  "Canada",
  "Costa Rica",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Guatemala",
  "Hong Kong",
  "Honduras",
  "Hungary",
  "Iceland",
  "Indonesia",
  "India",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jordan",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Lebanon",
  "Lithuania",
  "Latvia",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Netherlands",
  "Nepal",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Singapore",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Tunisia",
  "Turkmenistan",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const REGION_OPTIONS: Record<string, string[]> = {
  Australia: ["New South Wales", "Queensland", "Victoria", "Western Australia"],
  Canada: ["Alberta", "British Columbia", "Ontario", "Quebec"],
  Germany: ["Bavaria", "Berlin", "Hamburg", "Hesse"],
  India: ["Delhi", "Karnataka", "Maharashtra", "Tamil Nadu"],
  Pakistan: ["Balochistan", "Islamabad Capital Territory", "Khyber Pakhtunkhwa", "Punjab", "Sindh"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai", "Sharjah"],
  "United Kingdom": ["England", "Northern Ireland", "Scotland", "Wales"],
  "United States": ["California", "Florida", "Illinois", "New York", "Texas", "Washington"]
};

export const CITY_OPTIONS: Record<string, string[]> = {
  "Australia|New South Wales": ["Sydney", "Newcastle"],
  "Australia|Queensland": ["Brisbane", "Gold Coast"],
  "Australia|Victoria": ["Melbourne", "Geelong"],
  "Canada|Alberta": ["Calgary", "Edmonton"],
  "Canada|British Columbia": ["Vancouver", "Victoria"],
  "Canada|Ontario": ["Ottawa", "Toronto"],
  "Canada|Quebec": ["Montreal", "Quebec City"],
  "Germany|Berlin": ["Berlin"],
  "Germany|Bavaria": ["Munich", "Nuremberg"],
  "India|Delhi": ["New Delhi"],
  "India|Karnataka": ["Bengaluru", "Mysuru"],
  "India|Maharashtra": ["Mumbai", "Pune"],
  "India|Tamil Nadu": ["Chennai", "Coimbatore"],
  "Pakistan|Balochistan": ["Gwadar", "Quetta"],
  "Pakistan|Islamabad Capital Territory": ["Islamabad"],
  "Pakistan|Khyber Pakhtunkhwa": ["Abbottabad", "Peshawar"],
  "Pakistan|Punjab": ["Faisalabad", "Lahore", "Rawalpindi"],
  "Pakistan|Sindh": ["Hyderabad", "Karachi"],
  "United Arab Emirates|Abu Dhabi": ["Abu Dhabi", "Al Ain"],
  "United Arab Emirates|Dubai": ["Dubai"],
  "United Arab Emirates|Sharjah": ["Sharjah"],
  "United Kingdom|England": ["London", "Manchester"],
  "United Kingdom|Scotland": ["Edinburgh", "Glasgow"],
  "United States|California": ["Los Angeles", "San Francisco"],
  "United States|Florida": ["Miami", "Orlando"],
  "United States|Illinois": ["Chicago"],
  "United States|New York": ["New York City", "Buffalo"],
  "United States|Texas": ["Austin", "Dallas"],
  "United States|Washington": ["Seattle", "Spokane"]
};

export function getRegionOptions(country?: string) {
  return REGION_OPTIONS[country ?? ""] ?? [];
}

export function getCityOptions(country?: string, region?: string) {
  if (!country || !region) {
    return [];
  }

  return CITY_OPTIONS[`${country}|${region}`] ?? [];
}
