export const COUNTRY_OPTIONS = [
  "Worldwide",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Belarus",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const REGION_OPTIONS: Record<string, string[]> = {
  Australia: ["New South Wales", "Queensland", "Victoria", "Western Australia"],
  Canada: ["Alberta", "British Columbia", "Ontario", "Quebec"],
  Denmark: ["Capital Region of Denmark", "Central Denmark Region", "North Denmark Region", "Region Zealand", "Region of Southern Denmark"],
  Germany: ["Bavaria", "Berlin", "Hamburg", "Hesse"],
  Iceland: ["Capital Region", "Northeastern Region", "Southern Peninsula", "Southern Region", "Western Region"],
  India: ["Delhi", "Karnataka", "Maharashtra", "Tamil Nadu"],
  Pakistan: ["Balochistan", "Islamabad Capital Territory", "Khyber Pakhtunkhwa", "Punjab", "Sindh"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai", "Sharjah"],
  "United Kingdom": ["England", "Northern Ireland", "Scotland", "Wales"],
  "United States": ["California", "Florida", "Illinois", "New York", "Texas", "Washington"]
};

export const CITY_OPTIONS: Record<string, string[]> = {
  "Australia|New South Wales": ["Sydney", "Newcastle"],
  "Australia|Queensland": ["Brisbane", "Gold Coast"],
  "Australia|Victoria": ["Melbourne", "Geelong"],
  "Canada|Alberta": ["Calgary", "Edmonton"],
  "Canada|British Columbia": ["Vancouver", "Victoria"],
  "Canada|Ontario": ["Ottawa", "Toronto"],
  "Canada|Quebec": ["Montreal", "Quebec City"],
  "Denmark|Capital Region of Denmark": ["Copenhagen", "Hillerod"],
  "Denmark|Central Denmark Region": ["Aarhus", "Herning"],
  "Denmark|North Denmark Region": ["Aalborg", "Hjorring"],
  "Denmark|Region Zealand": ["Roskilde", "Naestved"],
  "Denmark|Region of Southern Denmark": ["Odense", "Esbjerg"],
  "Germany|Bavaria": ["Munich", "Nuremberg"],
  "Germany|Berlin": ["Berlin"],
  "Germany|Hamburg": ["Hamburg"],
  "Germany|Hesse": ["Frankfurt", "Wiesbaden"],
  "Iceland|Capital Region": ["Reykjavik", "Kopavogur"],
  "Iceland|Northeastern Region": ["Akureyri", "Husavik"],
  "Iceland|Southern Peninsula": ["Keflavik", "Reykjanesbaer"],
  "Iceland|Southern Region": ["Selfoss", "Vik"],
  "Iceland|Western Region": ["Akranes", "Borgarnes"],
  "India|Delhi": ["New Delhi"],
  "India|Karnataka": ["Bengaluru", "Mysuru"],
  "India|Maharashtra": ["Mumbai", "Pune"],
  "India|Tamil Nadu": ["Chennai", "Coimbatore"],
  "Pakistan|Balochistan": ["Gwadar", "Quetta"],
  "Pakistan|Islamabad Capital Territory": ["Islamabad"],
  "Pakistan|Khyber Pakhtunkhwa": ["Abbottabad", "Mardan", "Peshawar", "Swat"],
  "Pakistan|Punjab": ["Bahawalpur", "Faisalabad", "Gujranwala", "Lahore", "Multan", "Rawalpindi", "Sargodha", "Sialkot"],
  "Pakistan|Sindh": ["Hyderabad", "Karachi", "Sukkur"],
  "United Arab Emirates|Abu Dhabi": ["Abu Dhabi", "Al Ain"],
  "United Arab Emirates|Dubai": ["Dubai"],
  "United Arab Emirates|Sharjah": ["Sharjah"],
  "United Kingdom|England": ["London", "Manchester"],
  "United Kingdom|Northern Ireland": ["Belfast", "Derry"],
  "United Kingdom|Scotland": ["Edinburgh", "Glasgow"],
  "United Kingdom|Wales": ["Cardiff", "Swansea"],
  "United States|California": ["Los Angeles", "San Francisco"],
  "United States|Florida": ["Miami", "Orlando"],
  "United States|Illinois": ["Chicago"],
  "United States|New York": ["New York City", "Buffalo"],
  "United States|Texas": ["Austin", "Dallas"],
  "United States|Washington": ["Seattle", "Spokane"]
};

export function getRegionOptions(country?: string) {
  return REGION_OPTIONS[country ?? ""] ?? [];
}

export function getCityOptions(country?: string, region?: string) {
  if (!country || !region) {
    return [];
  }

  return CITY_OPTIONS[`${country}|${region}`] ?? [];
}
